services:
  spark-master:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-master
    command: ["master"]
    working_dir: /workspace
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    ports:
      - "7077:7077"
      - "8080:8080"
      - "6066:6066"
    volumes:
      - spark-history:/opt/spark/history
      - .:/workspace
    networks:
      - spark-net

  spark-worker:
    build:
      context: .
      dockerfile: spark/Dockerfile
    # container_name: spark-worker
    command: ["worker"]
    working_dir: /workspace
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
    # ports:
    #   - "8081:8081"
    volumes:
      - spark-history:/opt/spark/history
      - .:/workspace
    networks:
      - spark-net

  spark-history:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-history
    command: ["history"]
    working_dir: /workspace
    depends_on:
      - spark-master
    ports:
      - "18080:18080"
    volumes:
      - spark-history:/opt/spark/history
      - .:/workspace
    networks:
      - spark-net

volumes:
  spark-history:

networks:
  spark-net:
    driver: bridge
