# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recs_pb2 as recs__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendForUser = channel.unary_unary(
                '/recs.Recommender/RecommendForUser',
                request_serializer=recs__pb2.RecommendForUserRequest.SerializeToString,
                response_deserializer=recs__pb2.RecommendResponse.FromString,
                _registered_method=True)
        self.FoldInAndRecommend = channel.unary_unary(
                '/recs.Recommender/FoldInAndRecommend',
                request_serializer=recs__pb2.FoldInRequest.SerializeToString,
                response_deserializer=recs__pb2.RecommendResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/recs.Recommender/Health',
                request_serializer=recs__pb2.HealthRequest.SerializeToString,
                response_deserializer=recs__pb2.HealthResponse.FromString,
                _registered_method=True)


class RecommenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecommendForUser(self, request, context):
        """Simple top-K by user_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FoldInAndRecommend(self, request, context):
        """Fold-in a new user from recent (item_id, rating) and then recommend
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendForUser,
                    request_deserializer=recs__pb2.RecommendForUserRequest.FromString,
                    response_serializer=recs__pb2.RecommendResponse.SerializeToString,
            ),
            'FoldInAndRecommend': grpc.unary_unary_rpc_method_handler(
                    servicer.FoldInAndRecommend,
                    request_deserializer=recs__pb2.FoldInRequest.FromString,
                    response_serializer=recs__pb2.RecommendResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=recs__pb2.HealthRequest.FromString,
                    response_serializer=recs__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recs.Recommender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recs.Recommender', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Recommender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecommendForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recs.Recommender/RecommendForUser',
            recs__pb2.RecommendForUserRequest.SerializeToString,
            recs__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FoldInAndRecommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recs.Recommender/FoldInAndRecommend',
            recs__pb2.FoldInRequest.SerializeToString,
            recs__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recs.Recommender/Health',
            recs__pb2.HealthRequest.SerializeToString,
            recs__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
