# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrecs.proto\x12\x04recs\"O\n\x17RecommendForUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x18\n\x10\x65xclude_item_ids\x18\x03 \x03(\x03\"W\n\rFoldInRequest\x12\t\n\x01k\x18\x01 \x01(\x05\x12\x10\n\x08item_ids\x18\x02 \x03(\x03\x12\x0f\n\x07ratings\x18\x03 \x03(\x02\x12\x18\n\x10\x65xclude_item_ids\x18\x04 \x03(\x03\"5\n\x11RecommendResponse\x12\x10\n\x08item_ids\x18\x01 \x03(\x03\x12\x0e\n\x06scores\x18\x02 \x03(\x02\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xd2\x01\n\x0bRecommender\x12J\n\x10RecommendForUser\x12\x1d.recs.RecommendForUserRequest\x1a\x17.recs.RecommendResponse\x12\x42\n\x12\x46oldInAndRecommend\x12\x13.recs.FoldInRequest\x1a\x17.recs.RecommendResponse\x12\x33\n\x06Health\x12\x13.recs.HealthRequest\x1a\x14.recs.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDFORUSERREQUEST']._serialized_start=20
  _globals['_RECOMMENDFORUSERREQUEST']._serialized_end=99
  _globals['_FOLDINREQUEST']._serialized_start=101
  _globals['_FOLDINREQUEST']._serialized_end=188
  _globals['_RECOMMENDRESPONSE']._serialized_start=190
  _globals['_RECOMMENDRESPONSE']._serialized_end=243
  _globals['_HEALTHREQUEST']._serialized_start=245
  _globals['_HEALTHREQUEST']._serialized_end=260
  _globals['_HEALTHRESPONSE']._serialized_start=262
  _globals['_HEALTHRESPONSE']._serialized_end=294
  _globals['_RECOMMENDER']._serialized_start=297
  _globals['_RECOMMENDER']._serialized_end=507
# @@protoc_insertion_point(module_scope)
